### ISSUE TITLE
vterm-runner has an error when trying to reuse a buffer

### ISSUE THREAD

**Issue by ktfleming** [bard/emacs-run-command#20]
The first time I run a command with `run-command-runner-vterm`, it works fine. But if I try running the same command again, nothing happens other than I get an error:

> You cannot change major mode in vterm buffers

This seems to be because the vterm runner executes the command by setting `vterm-shell` and then calling `vterm-mode`: https://github.com/bard/emacs-run-command/blob/43afe908be26f13f5801dff69179aa64e74a235f/run-command-runner-vterm.el#L43-L44

But when the buffer is already using vterm-mode (as happens when re-running a command), it runs into this guard in vterm's code that prevents changing the major mode (even "changing" it from `vterm-mode` to `vterm-mode`):

https://github.com/akermu/emacs-libvterm/blob/990cc18decb489c54d16d03fd8acbfe268b98a9c/vterm.el#L757-L762

I haven't yet been able to think of a way around this other than locally disabling the "reuse buffer" feature and having it always generate a new buffer (which I believe was the behavior in older versions of run-command). Locally removing that guard in vterm's code and then re-running a command results in a different error: `vterm-mode: Buffer is read-only`. I suppose something, not sure what, in the code that runs when activating `vterm-mode` breaks when run in a read-only buffer. If I manually turn off read-only-mode in the command buffer and re-run the command again, the command re-uses the buffer as expected.

Unfortunately vterm doesn't seem to offer anything like `term-exec`, and the approach of setting `vterm-shell` is the only way I've found of having vterm run an arbitrary command.

**Comment by bard** [comment]
Thanks for the in-depth report!

Yes, ideally there would be a `vterm-exec` like there is `term-exec` and `eat-exec`, and yes, this got exposed because of the reuse of the output buffer introduced with the latest version.

The following hack seems to work in my very limited testing, could you check if it works for you at least for the time being?

```emacs-lisp
@@ -41,6 +41,8 @@ Executes COMMAND-LINE in buffer OUTPUT-BUFFER.  Name the process BUFFER-BASE-NAM
     (let ((vterm-kill-buffer-on-exit nil)
           ;; XXX needs escaping or commands containing quotes will cause trouble
           (vterm-shell (format "%s -c '%s'" vterm-shell command-line)))
+      (setq buffer-read-only nil)
+      (setq change-major-mode-hook nil)
       (vterm-mode))))
```
