### ISSUE TITLE
uniform buffer name

### ISSUE THREAD

**Issue by dchinmay2** [bard/emacs-run-command#23]
I use popper: https://github.com/karthink/popper which lets you toggle windows of "temporary" buffers

Can you make the names of the term buffers uniform so I can add that regex to my popper list? Like eglot for example: `"^\\*EGLOT"` - anything that starts with `*EGLOT`

**Comment by bard** [comment]
Not sure what naming scheme you're suggesting here (where would "EGLOT" come from in your example?) but you can already affect the buffer name by changing the `:command-name` field of the command definition in a recipe. 

Also, glancing at Popper's README, I see one can define popups by predicate, which I imagine would cover all scenarios.

**Comment by dchinmay2** [comment]
>  you can already affect the buffer name by changing the :command-name field of the command definition in a recipe.

ah right thanks

> Also, glancing at Popper's README, I see one can define popups by predicate, which I imagine would cover all scenarios.

How do I write this predicate? I got `:command-name` working but this seems better

**Comment by bard** [comment]
> > Also, glancing at Popper's README, I see one can define popups by predicate, which I imagine would cover all scenarios.
> 
> How do I write this predicate? I got `:command-name` working but this seems better

No idea, sorry, I'm not familiar with Popper beyond what I saw in the README.
