### ISSUE TITLE
FR: detached.el package integration

### ISSUE THREAD

**Issue by pataquets** [bard/emacs-run-command#25]
Thanks for sharing this package.
I'd like to run some commands and compilations and them to survive an Emacs close or crash. This can accomplished with [detached.el](https://sr.ht/~niklaseklund/detached.el/), which is an Emacs integration for [crigler/dtach](https://github.com/crigler/dtach).

Having the corresponding `run-command-runner-*-detached` variants would be great for integrating both packages.

**Comment by bard** [comment]
This would be better done in a separate package, as I wouldn't be the target user (I never close Emacs :)) so I'd be a terrible maintainer.

Once developed, it's easy to configure: https://bard.github.io/emacs-run-command/configuration#runner
