### ISSUE TITLE
Add support for default completion via completing-read

### ISSUE THREAD

**Issue by clemera** [bard/emacs-run-command#3]
As mentioned on reddit :)

**Comment by loafofpiecrust** [comment]
I would also like this as a selectrum user, esp. since it doesn't seem like you're using the ivy features that go beyond `completing-read`, meaning that could maybe replace your `ivy-read` implementation.

**Comment by bard** [comment]
@clemera @loafofpiecrust Can you have a look at https://github.com/bard/emacs-run-command/pull/5 and see if that works for you?

**Comment by oantolin** [comment]
I haven't run this code, but from a quick look at the source, I agree with @loafofpiecrust. It does look like you could probably just use `completing-read` and delete all the Ivy and Helm specific code.

**Comment by leungbk** [comment]
> It does look like you could probably just use `completing-read` and delete all the Ivy and Helm specific code.

Getting the `ivy` wrapper to work with `ivy-resume` and `ivy-reverse-i-search` requires a `:caller` and `:history` respectively in an `ivy-read` invocation. So I think it might be worth keeping that stuff around.

**Comment by bard** [comment]
While I'd also prefer to target just the lowest layer (and I think the new completion tools are doing the right thing in working at that level), from a quick test that in this case I see that we'd lose Helm's headers (minor) and adaptive sort (bigger issue for me), and close some doors that Ivy's users might prefer left open, as per @leungbk's comment. I'm keeping separate integrations for now, and revisit in the future.

I merged initial support for `completing-read`, it will be chosen automatically when `run-command-completion-method` is `auto` (the default) and neither `helm-mode` nor `ivy-mode` are active.
