### ISSUE TITLE
feature request: running elisp functions instead of shell ones?

### ISSUE THREAD

**Issue by hai-nc** [bard/emacs-run-command#7]
Nice project!

I wonder if a feature could be added so that run-command execute elisp functions instead of shell ones? 

It would help me avoid making regular elisp commands (along with a "package" prefix for them, which pollutes the global namespace) just for some specific projects. 

Furthermore, this feature would let run-command execute elisp functions instead of just limited to executing shell commands.

**Comment by bard** [comment]
I added a minimal implementation in the `lisp-commands` branch, to try it set `:command-line` to a lambda instead of a string, e.g.:

```emacs-lisp
(defun run-command-recipe-local ()
  (list
   (list :command-name "lisp-command-example-1"
         :command-line (lambda () (message "Hello, world!")))))
```

Summarizing the other bits of the conversation on Reddit, for reference:

- a mechanism for calling Lisp code exists already (`M-x` and interactive functions); by adding another, there's a risk that the user's flow will break at the time of invoking a command, to remember which of the two mechanisms is needed;
- this strategy pre-filters commands relevant to the context, helping memory and discoverability, and doesn't pollute the global namespace for otherwise context-specific functionality;
- won't be included in the short term, to keep `run-command` focused on the core goal, but experimentation is welcome and depending on experiences it might make its way into the package.

An interesting difference that I hadn't considered until actually using the branch is that shell commands are assumed to have an output buffer, Lisp functions aren't.

**Comment by hai-nc** [comment]
Thanks for your quick response. I will try it out.

Just a quick note, would it be less confusing to avoid using :command-line for both shell syntax and elisp ones? Perhaps something like this would be clearer:

`(defun run-command-recipe-local ()
  (list
   (list :command-name "lisp-command-example-1"
         :elisp (lambda () (message "Hello, world!")))))`

**Comment by hai-nc** [comment]
I tried the git branch 'lisp-command' but I could not get `run-command' to execute properly. I am using Emacs 27.1 debian on Debian Sid and this is what I did:

```lisp
(add-to-list 'load-path <my-path-to-run-command>)
(load "run-command")

(defun run-command-recipe-local ()
   ... ; copy and paste code from the README file
 )
```

Then I M-x run-command and it query me but with no options to choose from, ie. the list of commands to choose from is empty and it broke there :( .

The error message I got:

```lisp
  cdr("say-hello")
  (let* ((command-spec (cdr selection)) (command-line (plist-get command-spec :command-line)) (final-command-line (if ivy-current-prefix-arg (read-string "> " (concat command-line " ")) command-line))) (run-command--run (plist-put command-spec :command-line final-command-line)))
  run-command--ivy-action("say-hello")
  ivy-call()
  #f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes one argument, the selected candidate. If COLLECTION is\nan alist, the argument is a cons cell, otherwise it's a string.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nEXTRA-PROPS is a plist that can be used to store\ncollection-specific session-specific data.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x15621aef0ea5>)("Command Name: " nil :action run-command--ivy-action)
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes one argument, the selected candidate. If COLLECTION is\nan alist, the argument is a cons cell, otherwise it's a string.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nEXTRA-PROPS is a plist that can be used to store\ncollection-specific session-specific data.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x15621aef0ea5>) ("Command Name: " nil :action run-command--ivy-action))
  ivy-read("Command Name: " nil :action run-command--ivy-action)
  (if (window-minibuffer-p) nil (ivy-read "Command Name: " (run-command--ivy-targets) :action 'run-command--ivy-action))
  run-command--ivy()
  (cond ((and (boundp 'helm-mode) helm-mode) (run-command--helm)) ((and (boundp 'ivy-mode) ivy-mode) (run-command--ivy)) (t (run-command--completing-read)))
  (cond ((eq run-command-completion-method 'auto) (cond ((and (boundp 'helm-mode) helm-mode) (run-command--helm)) ((and (boundp 'ivy-mode) ivy-mode) (run-command--ivy)) (t (run-command--completing-read)))) ((eq run-command-completion-method 'helm) (run-command--helm)) ((eq run-command-completion-method 'ivy) (run-command--ivy)) ((eq run-command-completion-method 'completing-read) (run-command--completing-read)) (t (error "Unrecognized completion method: %s" run-command-completion-method)))
  run-command()
  (progn (run-command))
  eval((progn (run-command)) t)
...
```

**Comment by bard** [comment]
> I tried the git branch 'lisp-command' but I could not get `run-command' to execute properly

Remember to also configure `run-command-recipes`, either by customizing it or with:

```emacs-lisp
(add-to-list 'run-command-recipes 'run-command-recipe-local)
```

> would it be less confusing to avoid using :command-line for both shell syntax and elisp ones

Yes, it's confusing to have both assigned to `:command-line`. If the feature makes its way into the package, rather than specifying shell commands and Lisp functions via separate properties, I think they could be specified by a single property with a neutral name, such as `:exec` or `:run`. I'm not renaming it now in the branch to make it easier to keep the branch up to date with master.

**Comment by hai-nc** [comment]
Thanks. I got it working now. The feature ran smoothly for my use case, which is quite simple though - making commands to opening different links in an org buffer. 

I have yet seen the instruction to customize or set _run-command-recipes_ in the README file, so I guess it could be added for clarity for new users.

**Comment by bard** [comment]
They're in the [quickstart](https://github.com/bard/emacs-run-command/#quickstart); maybe they get pushed out of attention by the big chunk of code above. I'll add them to the configuration section, too, and maybe make that chunk smaller. Thanks for mentioning it.

**Comment by hai-nc** [comment]
Yeah sorry I missed that line in the quickstart.

I wonder why not set _run-command-recipes_ to _'run-command-recipe-local_ by default?

**Comment by bard** [comment]
The names of recipes are up to the user as much as the content.

Apart from additional documentation, there is now an error message warning the user when `run-command` gets called with an empty `run-command-recipes`, which should address the UX part of the misconfiguration issue properly.
 
(Let's keep this issue focused on the Lisp functions experiment, though.)

**Comment by bard** [comment]
Now available as an [experiment](https://github.com/bard/emacs-run-command#experimental-features) in master branch, merging of example will also follow.
